version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - '15432:5432'
    env_file:
      - .env
    restart: always
    volumes: 
      - ./00-postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
      - ./postgres-data:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    env_file:
      - .env
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql

  hasura:
    image: hasura/graphql-engine:latest
    ports:
      - '8084:8080'
    depends_on:
      - 'postgres'
    env_file:
      - .env
    restart: always

  postgres-client:
    image: postgres:latest
    ports:
      - '15433:5432'
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=yoursupersecret
    restart: always
    volumes: 
      - ./postgres-client-data:/var/lib/postgresql/data