---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tox targets for ${{ matrix.python-version }}
        run: |
          source venv/bin/activate
          python -m unittest tests.related_tables

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Deploy on GPT 3 server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd /tmp
          rm -r Text2SQL
          git clone https://github.com/ChakshuGautam/Text2SQL.git
          cd Text2SQL
          cp .env.sample .env
          echo -en "\nBASIC_AUTH_USERNAME=${{ secrets.APP_USERNAME }}\n" >> .env
          echo -en "\nBASIC_AUTH_PASSWORD=${{ secrets.APP_PASSWORD }}\n" >> .env
          echo -en "\nOPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}\n" >> .env
          docker-compose up -d --build
          sh setup.sh
